---
title: "Sentence Bias Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
results <- read_tsv('results.tsv')
hb <- function(data) {
  data %>%
    arrange(p_value) %>%
    mutate(rank=row_number(),
           p_value_threshold=0.01/(n() + 1 - rank),
           reject=rank < min(which(p_value > p_value_threshold))) %>%
    arrange(model, options, test)
}
```

```{r}
results %>% head
```

## Exploration

### All combinations

```{r}
results %>%
  select(model, options) %>%
  unique
```

```{r}
results %>%
  select(test) %>%
  unique
```

```{r fig.width=10,fig.height=16}
results %>%
  hb %>%
  mutate(model_options=ifelse(is.na(options), model, str_c(model, ';', options))) %>%
  mutate(significance=factor(1 + (p_value <= 0.01) + reject, levels=1:3, labels=c('insignificant', 'significant at 0.01', 'signif at 0.01 after correction'))) %>%
  select(-model) %>%
  rename(model=model_options) %>%
  ggplot() +
  geom_tile(aes(x=model, y=test, fill=significance)) +
  scale_fill_brewer(palette=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))
ggsave('legend.pdf', width=8, height=9)
```

### Selected models

```{r fig.width=7.5,fig.height=16}
selected_model_options = c(
   'bow',
   'infersent',
   'guse',
   'gensen;version=nli_large_bothskip_parse,nli_large_bothskip',
   'elmo;time_combine=mean;layer_combine=add',
   'openai',
   'bert;version=bert-large-cased')
results %>%
  hb %>%
  mutate(model_options=ifelse(is.na(options), model, str_c(model, ';', options))) %>%
  filter(model_options %in% selected_model_options) %>%
  mutate(significance=factor(1 + (p_value <= 0.01) + reject, levels=1:3, labels=c('insignificant', 'significant at 0.01', 'signif at 0.01 after correction'))) %>%
  ggplot() +
  geom_tile(aes(x=model, y=test, fill=significance)) +
  scale_fill_brewer(palette=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

### WEAT 3-5

```{r}
results %>%
  hb %>%
  mutate(model_options=ifelse(is.na(options), model, str_c(model, ';', options))) %>%
  filter(str_detect(test, 'weat[3-5]$')) %>%
  ggplot() +
  geom_tile(aes(x=model_options, y=test, fill=-log10(p_value))) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

```{r}
results %>%
  hb %>%
  mutate(model_options=ifelse(is.na(options), model, str_c(model, ';', options))) %>%
  filter(str_detect(test, 'weat[3-5]$')) %>%
  select(model_options, test, p_value) %>%
  spread(model_options, p_value)
```

### WEAT 7-8

```{r}
results %>%
  hb %>%
  mutate(model_options=ifelse(is.na(options), model, str_c(model, ';', options))) %>%
  filter(str_detect(test, 'weat[7-8]$')) %>%
  ggplot() +
  geom_tile(aes(x=model_options, y=test, fill=-log10(p_value))) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

```{r}
results %>%
  hb %>%
  mutate(model_options=ifelse(is.na(options), model, str_c(model, ';', options))) %>%
  filter(str_detect(test, 'weat[7-8]$')) %>%
  select(model_options, test, p_value) %>%
  spread(model_options, p_value)
```

### BOW, WEAT word-level

```{r}
results %>%
  hb %>%
  filter(model == 'bow', str_detect(test, '^weat[0-9]+$')) %>%
  arrange(as.numeric(str_extract(test, '[0-9]+'))) %>%
  select(test, p_value, effect_size)
```

### USE, WEAT word-level

```{r}
results %>%
  hb %>%
  filter(model == 'guse', str_detect(test, '^weat[0-9]+$')) %>%
  arrange(as.numeric(str_extract(test, '[0-9]+'))) %>%
  select(test, p_value, effect_size)
```

## Set sizes

```{r}
results %>%
  select(test, num_targ1, num_targ2, num_attr1, num_attr2) %>%
  unique
```

## Controlling for multiple hypothesis tests

### Overall

Using Holm-Bonferroni procedure:

```{r}
results %>%
  hb %>%
  filter(reject)
```

### Effect sizes of selected models

```{r}
model_levels <- c('CBoW', 'InferSent', 'GenSen', 'USE', 'ELMo', 'GPT', 'BERT')
rename_model <- function(model) {
  if (model == 'bert') {
    'BERT'
  } else if (model == 'bow') {
    'CBoW'
  } else if (model == 'elmo') {
    'ELMo'
  } else if (model == 'gensen') {
    'GenSen'
  } else if (model == 'guse') {
    'USE'
  } else if (model == 'infersent') {
    'InferSent'
  } else if (model == 'openai') {
    'GPT'
  } else {
    model
  }
}
rename_test <- function(test) {
  test %>%
    str_remove('^sent-') %>%
    str_replace('^heilman_double_bind', 'DB') %>%
    str_replace('^angry_black_woman_stereotype', 'ABW_stereotype') %>%
    str_replace('^weat', 'Caliskan_') %>%
    str_remove('_one_word$') %>%
    str_remove('_one_sentence$') %>%
    str_replace_all('_', ' ')
}
test_levels <- rev(c(
  'Caliskan 1',
  'Caliskan 2',
  'Caliskan 3',
  'Caliskan 4',
  'Caliskan 5',
  'Caliskan 6',
  'Caliskan 7',
  'Caliskan 8',
  'Caliskan 9',
  'Caliskan 10',
  'ABW stereotype',
  'DB competent',
  'DB likable'
))
signif_results <- results %>%
  hb %>%
  #filter(reject) %>%
  mutate(effect_size=ifelse(reject, effect_size, 0))
```

```{r fig.width=5,fig.height=3.5}
clean_word_effects <- signif_results %>%
  filter(! str_detect(test, '[0-9]b$'), ! str_detect(test, '_b$'), ! str_detect(test, '_1[+-3]*$')) %>%
  filter(! str_detect(test, '^sent-'), ! str_detect(test, '_one_sentence$')) %>%
  mutate(model_options=ifelse(is.na(options), model, str_c(model, ';', options))) %>%
  filter(model_options %in% selected_model_options) %>%
  rowwise() %>% 
  mutate(model=factor(rename_model(model), levels=model_levels),
         test=factor(rename_test(test), levels=test_levels),
         level='word-level')
clean_sent_effects <- signif_results %>%
  filter(! str_detect(test, '[0-9]b$'), ! str_detect(test, '_b$'), ! str_detect(test, '_1[+-3]*$')) %>%
  filter(str_detect(test, '^sent-') | str_detect(test, '_one_sentence$'), ! str_detect(test, '^sent-heilman')) %>%
  mutate(model_options=ifelse(is.na(options), model, str_c(model, ';', options))) %>%
  filter(model_options %in% selected_model_options) %>%
  rowwise() %>% 
  mutate(model=factor(rename_model(model), levels=model_levels),
         test=factor(rename_test(test), levels=test_levels),
         level='sentence-level')
clean_word_effects %>%
  rbind(clean_sent_effects) %>%
  ggplot() +
  geom_tile(aes(x=model, y=test, fill=effect_size)) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  scale_fill_gradient(low='white', high='darkblue', limits=c(0,2)) +
  facet_grid(. ~ level)
ggsave('significant_effects.png', width=5, height=3.5)
```

## Validity

### Validity 1

```{r fig.width=4,fig.height=2.5}
v1_test_map <- c('Caliskan 5'='16,8',
                 'Caliskan 4'='16,25',
                 'Caliskan 3'='32,25')
results %>%
  filter(model %in% c('elmo', 'bow'),
         test %in% c('weat3', 'weat4', 'weat5', 'sent-weat3', 'sent-weat4', 'sent-weat5')) %>%
  mutate(model_options=ifelse(is.na(options), model, str_c(model, ';', options))) %>%
  filter(model_options %in% selected_model_options) %>%
  mutate(sent=str_detect(test, '^sent-'),
         test=str_remove(test, '^sent-'),
         level=ifelse(sent, 'sentence-level', 'word-level')) %>%
  rowwise() %>% 
  mutate(model=factor(rename_model(model), levels=model_levels),
         sample_size=factor(v1_test_map[rename_test(test)], v1_test_map)) %>%
  ggplot(aes(x=sample_size, group=model, colour=model, shape=model, y=p_value)) +
  geom_line(size=1) +
  geom_point(size=4) +
  scale_y_log10() +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  facet_grid(. ~ level)
ggsave('validity_1.png', width=4, height=2.5)
```


### Validity 2

```{r fig.width=4,fig.height=2.5}
results %>%
  filter(model %in% c('bow', 'bert', 'gensen', 'openai'),
         test %in% c('weat7', 'weat8', 'sent-weat7', 'sent-weat8')) %>%
  mutate(model_options=ifelse(is.na(options), model, str_c(model, ';', options))) %>%
  filter(model_options %in% selected_model_options) %>%
  mutate(sent=str_detect(test, '^sent-'),
         test=str_remove(test, '^sent-'),
         level=ifelse(sent, 'sentence-level', 'word-level')) %>%
  rowwise() %>% 
  mutate(model=factor(rename_model(model), levels=model_levels),
         test=factor(rename_test(test), rev(test_levels))) %>%
  ggplot(aes(x=test, group=model, colour=model, shape=model, y=p_value)) +
  geom_line(size=1) +
  geom_point(size=4) +
  scale_y_log10() +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  facet_grid(. ~ level)
ggsave('validity_2.png', width=4, height=2.5)
```
